export const FETCH_UPCOMING_MATCHES_START = 'FETCH_UPCOMING_MATCHES_START';
export const FETCH_UPCOMING_MATCHES_FAILED = 'FETCH_UPCOMING_MATCHES_FAILED';
export const FETCH_UPCOMING_MATCHES_SUCCESS = 'FETCH_UPCOMING_MATCHES_SUCCESS';

export const ADD_UPCOMING_MATCH = 'ADD_UPCOMING_MATCH';

export const DELETE_MATCH_FROM_UPCOMING_MATCHES = 'DELETE_MATCH_FROM_UPCOMING_MATCHES';

export const INIT_MATCH_RESULT_INPUT = 'INIT_MATCH_RESULT_INPUT';

export const ADD_MATCH_RESULT = 'ADD_MATCH_RESULT';

export const ADD_MATCH_RESULT_START = 'ADD_MATCH_RESULT_START';
export const ADD_MATCH_RESULT_SUCCESS = 'ADD_MATCH_RESULT_SUCCESS';
export const ADD_MATCH_RESULT_FAIL = 'ADD_MATCH_RESULT_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_COMPLETED_MATCHES = 'FETCH_COMPLETED_MATCHES';
export const FETCH_COMPLETED_MATCHES_SUCCESS = 'FETCH_COMPLETED_MATCHES_SUCCESS';
export const FETCH_COMPLETED_MATCHES_START = 'FETCH_COMPLETED_MATCHES_START';
export const FETCH_COMPLETED_MATCHES_FAIL = 'FETCH_COMPLETED_MATCHES_FAIL';

export const INIT_MATCH_PREDICTION_INPUT = 'INIT_MATCH_PREDICTION_INPUT';
export const ADD_MATCH_PREDICTION_START = 'ADD_MATCH_PREDICTION_START';
export const ADD_MATCH_PREDICTION_FAIL = 'ADD_MATCH_PREDICTION_FAIL';
export const ADD_MATCH_PREDICTION_SUCCESS = 'ADD_MATCH_PREDICTION_SUCCESS';

export const ADD_MATCH_PREDICTION = 'ADD_MATCH_PREDICTION';






