export const FETCH_UPCOMING_MATCHES_START = 'FETCH_UPCOMING_MATCHES_START';
export const FETCH_UPCOMING_MATCHES_FAILED = 'FETCH_UPCOMING_MATCHES_FAILED';
export const FETCH_UPCOMING_MATCHES_SUCCESS = 'FETCH_UPCOMING_MATCHES_SUCCESS';

export const ADD_UPCOMING_MATCH = 'ADD_UPCOMING_MATCH';

export const DELETE_MATCH_FROM_UPCOMING_MATCHES = 'DELETE_MATCH_FROM_UPCOMING_MATCHES';

export const INIT_MATCH_RESULT_OR_PREDICTION_INPUT = 'INIT_MATCH_RESULT_OR_PREDICTION_INPUT';

export const ADD_MATCH_RESULT_OR_PREDICTION = 'ADD_MATCH_RESULT_OR_PREDICTION';

export const ADD_MATCH_RESULT_OR_PREDICTION_START = 'ADD_MATCH_RESULT_OR_PREDICTION_START';
export const ADD_MATCH_RESULT_OR_PREDICTION_SUCCESS = 'ADD_MATCH_RESULT_OR_PREDICTION_SUCCESS';
export const ADD_MATCH_RESULT_OR_PREDICTION_FAIL = 'ADD_MATCH_RESULT_OR_PREDICTION_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_COMPLETED_MATCHES = 'FETCH_COMPLETED_MATCHES';
export const FETCH_COMPLETED_MATCHES_SUCCESS = 'FETCH_COMPLETED_MATCHES_SUCCESS';
export const FETCH_COMPLETED_MATCHES_START = 'FETCH_COMPLETED_MATCHES_START';
export const FETCH_COMPLETED_MATCHES_FAIL = 'FETCH_COMPLETED_MATCHES_FAIL';

export const FETCH_USER_PREDICTIONS = 'FETCH_USER_PREDICTIONS';
export const FETCH_USER_PREDICTIONS_SUCCESS = 'FETCH_USER_PREDICTIONS_SUCCESS';
export const FETCH_USER_PREDICTIONS_START = 'FETCH_USER_PREDICTIONS_START';
export const FETCH_USER_PREDICTIONS_FAIL = 'FETCH_USER_PREDICTIONS_FAIL';

export const FETCH_UPCOMING_PREDICTIONS_START = 'FETCH_UPCOMING_PREDICTIONS_START';
export const FETCH_UPCOMING_PREDICTIONS_FAIL = 'FETCH_UPCOMING_PREDICTIONS_FAIL';
export const FETCH_UPCOMING_PREDICTIONS_SUCCESS = 'FETCH_UPCOMING_PREDICTIONS_SUCCESS';

export const CREATE_MATCHES_PREDICTIONS_ARRAY = 'CREATE_MATCHES_PREDICTIONS_ARRAY';

export const UPDATE_PREDICTION_START = 'UPDATE_PREDICTION_START';
export const UPDATE_PREDICTION_SUCCESS = 'UPDATE_PREDICTION_SUCCESS';
export const UPDATE_PREDICTION_FAIL = 'UPDATE_PREDICTION_FAIL';
export const INIT_UPDATE_PREDICTION = 'INIT_UPDATE_PREDICTION';








