export const FETCH_UPCOMING_MATCHES_START = 'FETCH_UPCOMING_MATCHES_START';
export const FETCH_UPCOMING_MATCHES_FAILED = 'FETCH_UPCOMING_MATCHES_FAILED';
export const FETCH_UPCOMING_MATCHES_SUCCESS = 'FETCH_UPCOMING_MATCHES_SUCCESS';

export const ADD_UPCOMING_MATCH = 'ADD_UPCOMING_MATCH';

export const ADD_MATCH_RESULT = 'ADD_MATCH_RESULT';

export const DELETE_MATCH_FROM_UPCOMING_MATCHES = 'DELETE_MATCH_FROM_UPCOMING_MATCHES';

export const INIT_MATCH_RESULT_INPUT = 'INIT_MATCH_RESULT_INPUT';